import type { Species } from './types'

// Concept: docs/concepts/dewdrop.png. H is the upper-left highlight;
// O is the warm outline. Facial features are supplied entirely by the engine.
export const dewdrop: Species = {
  id: 'dewdrop',
  name: '滴露灵',
  description: '软软的小露珠长出歪歪水滴帽，踩着三瓣水花慢悠悠地晃。',
  nameEn: 'Dewdrop',
  descriptionEn: 'A soft little dewdrop that grows a lopsided drop hat and bobs along on three-petal splashes.',
  colors: {
    O: 0x45344c,
    H: 0xe5fff3,
    F: 0xbef1df,
    B: 0x67c7c1,
    S: 0x437d87,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '......O......',
        '.....OHO.....',
        '...OOHBOOO...',
        '..OHFFFFFFOO.',
        '.OFFFFFFFFFBO',
        '.OFFFFFFFFFBO',
        '.OFFFFFFFFFBO',
        '.OBFFFFFFFFBO',
        '..OBSBOBBSOO.',
        '...OOO.OOO...',
      ],
      alt: [
        '.....O.......',
        '.....OOO.....',
        '...OOHBOOO...',
        '..OHFFFFFFOO.',
        '.OFFFFFFFFFBO',
        '.OFFFFFFFFFBO',
        '.OFFFFFFFFFBO',
        '.OBFFFFFFFFBO',
        '.OOBSBOBBBOOO',
        '...OOO.OOO...',
      ],
      eyes: [[3,4],[7,4]],
      mouth: [5,6],
    },
    child: {
      body: [
        '.....OOO.......',
        '....OHBBO......',
        '....OHBO.......',
        '...OHBBOOO.....',
        '..OHFFFFFFOO...',
        '.OFFFFFFFFFBO..',
        '.OFFFFFFFFFBO..',
        'OHFFFFFFFFFBBO.',
        'OSBFFFFFFFFBSO.',
        '.OBBSOBBOBSBO..',
        '..OOO.OO.OOO...',
      ],
      alt: [
        '....OOO........',
        '...OHBBO.......',
        '...OHBBO.......',
        '...OHBBOOO.....',
        '..OHFFFFFFOO...',
        '.OFFFFFFFFFBO..',
        '.OFFFFFFFFFBO..',
        'OBFFFFFFFFFBHO.',
        '.OBFFFFFFFFBO..',
        '.OBBSOBBOBSBO..',
        '..OOO.OO.OOO...',
      ],
      eyes: [[3,5],[7,5]],
      mouth: [5,7],
    },
    teen: {
      body: [
        '.....OOOO.........',
        '....OHHBBO........',
        '...OHOOBBBO.......',
        '...OO.OBBBO.......',
        '.....OHHBBBO......',
        '....OHFFFFFFO.....',
        '...OFFFFFFFFFO....',
        '..OBFFFFFFFFFBO...',
        '.OHBFFFFFFFFFBBO..',
        '.OSBBFFFFFFFFBSO..',
        '..OBBFFFFFFFFBO...',
        '...OBSBOBSOBSO....',
        '....OOO.OO.OO.....',
      ],
      alt: [
        '....OOOO..........',
        '...OHHBBOO........',
        '...OHOOBBBO.......',
        '....O.OBBBO.......',
        '.....OHHBBBO......',
        '....OHFFFFFFO.....',
        '...OFFFFFFFFFO....',
        '..OBFFFFFFFFFBO...',
        '.OBBFFFFFFFFFBHO..',
        '..OBBFFFFFFFFBO...',
        '..OBBFFFFFFFFBO...',
        '...OBSBOBSOBSO....',
        '....OOO.OO.OO.....',
      ],
      eyes: [[5,6],[9,6]],
      mouth: [7,8],
    },
    adult: {
      body: [
        '.....OOOOO.........',
        '....OHHHBBO........',
        '...OHBOBBBBO.......',
        '...OHO.OBBBBO......',
        '....O..OHBBBO......',
        '......OHHBBBBO.....',
        '.....OHFFFFFFBO....',
        '....OFFFFFFFFFBO...',
        '...OBFFFFFFFFFBBO..',
        '..OHBFFFFFFFFFBBBO.',
        '..OSBBFFFFFFFFBBSO.',
        '...OBBFFFFFFFFBBO..',
        '...OBBSSBBBBSSBOO..',
        '....OBBOBBOBBBO....',
        '.....OO.OO.OOO.....',
      ],
      alt: [
        '....OOOOO..........',
        '...OHHHBBO.........',
        '..OHBOOBBBO........',
        '..OHO..OBBBOO......',
        '...O...OHBBBO......',
        '......OHHBBBBO.....',
        '.....OHFFFFFFBO....',
        '....OFFFFFFFFFBO...',
        '...OBFFFFFFFFFBBO..',
        '..OBBFFFFFFFFFBBHO.',
        '...OBBFFFFFFFFBBO..',
        '...OBBFFFFFFFFBBO..',
        '...OBBSSBBBBSSBOO..',
        '....OBBOBBOBBBO....',
        '.....OO.OO.OOO.....',
      ],
      eyes: [[6,7],[10,7]],
      mouth: [8,9],
    },
  },
}
