import type { Species } from './types'

// Concept: docs/concepts/inkfold.png. The face is deliberately blank;
// the engine supplies all eyes, blush and mouths in both animation frames.
export const inkfold: Species = {
  id: 'inkfold',
  name: '折墨猫',
  description: '石墨色纸页折成的小猫，长大后展开金边折角尾，把爪爪收成小纸包。',
  nameEn: 'Inkfold',
  descriptionEn: 'A kitten folded from graphite paper, growing a gold-tipped zigzag tail and neatly tucked paper paws.',
  colors: {
    O: 0x42353e,
    B: 0x918c93,
    S: 0x625763,
    F: 0xdcd6ca,
    H: 0xfff6de,
    G: 0xd6b568,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '..O.......O.....',
        '.OHO.....OSO....',
        '.OBFOOOOOBSO....',
        'OBFFFFFFFFBBO...',
        'OBFFFFFFFFBBO.O.',
        'OBFFFFFFFFBSSOBO',
        'OBFFFFFFFFBBSSO.',
        '.OBBBBBBBBBBBSO.',
        '..OHBBOBHBBOHO..',
        '..OOOO.OOOO.OO..',
      ],
      alt: [
        '..O.......O.....',
        '.OHO.....OSO....',
        '.OBFOOOOOBSO....',
        'OBFFFFFFFFBBO...',
        'OBFFFFFFFFBBOO..',
        'OBFFFFFFFFBSSOOO',
        'OBFFFFFFFFBBSSO.',
        '.OBBBBBBBBBBBSO.',
        '..OHBBOBHBBOHO..',
        '..OOOO.OOOO.OO..',
      ],
      eyes: [[3, 3], [7, 3]],
      mouth: [5, 5],
    },
    child: {
      body: [
        '..O.......O.......',
        '.OHO.....OSO......',
        '.OBBOOOOOBSO....O.',
        'OBBFFFFFFBSBO..OBO',
        'OBFFFFFFFFBBO.OBO.',
        'OBFFFFFFFFBBO..OBO',
        'OBFFFFFFFFBSSOOBO.',
        '.OFFFFFFFFBBSSBBO.',
        '..OBBBBBBBBBBSSO..',
        '..OHBBOBHBBOBBO...',
        '..OOOO.OOOO.OOO...',
      ],
      alt: [
        '..O.......O.......',
        '.OHO.....OSO......',
        '.OBBOOOOOBSO...O..',
        'OBBFFFFFFBSBO.OBO.',
        'OBFFFFFFFFBBOOBO..',
        'OBFFFFFFFFBBO.OBO.',
        'OBFFFFFFFFBSSOOBO.',
        '.OFFFFFFFFBBSSBBO.',
        '..OBBBBBBBBBBSSO..',
        '..OHBBOBHBBOBBO...',
        '..OOOO.OOOO.OOO...',
      ],
      eyes: [[3, 4], [7, 4]],
      mouth: [5, 6],
    },
    teen: {
      body: [
        '..O.......O.......O.',
        '.OHO.....OSO.....OBO',
        '.OBBOOOOOBSO....OBO.',
        'OBBFFFFFFBSBO....OBO',
        'OBFFFFFFFFBBO...OBO.',
        'OBFFFFFFFFBBO..OBO..',
        'OBFFFFFFFFBSSOOBBO..',
        '.OFFFFFFFFBBSSBBBO..',
        '..OBGGBGGBBBBSSBBO..',
        '..OBBBGBBBBBBBSSO...',
        '..OHBBOBHBBOOBBO....',
        '..OOOO.OOOO..OOO....',
      ],
      alt: [
        '..O.......O......O..',
        '.OHO.....OSO....OBO.',
        '.OBBOOOOOBSO...OBO..',
        'OBBFFFFFFBSBO...OBO.',
        'OBFFFFFFFFBBO..OBO..',
        'OBFFFFFFFFBBO.OBO...',
        'OBFFFFFFFFBSSOOBBO..',
        '.OFFFFFFFFBBSSBBBO..',
        '..OBGGBGGBBBBSSBBO..',
        '..OBBBGBBBBBBBSSO...',
        '..OHBBOBHBBOOBBO....',
        '..OOOO.OOOO..OOO....',
      ],
      eyes: [[3, 4], [7, 4]],
      mouth: [5, 6],
    },
    adult: {
      body: [
        '...................OO.',
        '..................OGGO',
        '..O.......O.......OGGO',
        '.OHO.....OSO.......OBO',
        '.OBBOOOOOBSO.....OOBO.',
        'OBBFFFFFFBSBO...OBBO..',
        'OBFFFFFFFFBBO....OBBO.',
        'OBFFFFFFFFBBO.....OBOO',
        'OBFFFFFFFFBSSOOOOOBO..',
        '.OFFFFFFFFBBSSBBBBBO..',
        '..OBGGBGGBBBBSSBBBO...',
        '..OBBBGBBBBBBBSSBO....',
        '..OHBBOBHBBOOBBSO.....',
        '..OOOO.OOOO..OOOO.....',
      ],
      alt: [
        '..................OO..',
        '.................OGGO.',
        '..O.......O......OGGO.',
        '.OHO.....OSO......OBO.',
        '.OBBOOOOOBSO....OOBO..',
        'OBBFFFFFFBSBO..OBBO...',
        'OBFFFFFFFFBBO...OBBO..',
        'OBFFFFFFFFBBO....OBOO.',
        'OBFFFFFFFFBSSOOOOOBO..',
        '.OFFFFFFFFBBSSBBBBBO..',
        '..OBGGBGGBBBBSSBBBO...',
        '..OBBBGBBBBBBBSSBO....',
        '..OHBBOBHBBOOBBSO.....',
        '..OOOO.OOOO..OOOO.....',
      ],
      eyes: [[3, 6], [7, 6]],
      mouth: [5, 8],
    },
  },
}
