import type { Species } from './types'

// Concept: docs/concepts/kilnby.png. The face is deliberately blank;
// the engine supplies all eyes, blush and mouths in both animation frames.
export const kilnby: Species = {
  id: 'kilnby',
  name: '陶火犬',
  description: '赤陶做的软耳小狗，奶油釉染上胸口，长大后尾巴弯成一只小把手。',
  nameEn: 'Kilnby',
  descriptionEn: 'A floppy-eared terracotta puppy with a cream-glazed bib and a tail that grows into a tiny pottery handle.',
  colors: {
    O: 0x48302e,
    B: 0xc37965,
    S: 0x804b46,
    F: 0xecd8ba,
    H: 0xfff0d8,
    G: 0x91ab94,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '.....OOOOO.......',
        '...OOBBBBBOO.....',
        '.OOBHHFFFFBOOO...',
        'OBOFFFFFFFFOBBO..',
        'OBOFFFFFFFFOBBO..',
        'OBOFFFFFFFFOSSBOO',
        'OBOFFFFFFFFOSSBBO',
        '.OOBBBBBBBBSOOBO.',
        '..OFBBOBFBBOFBO..',
        '..OOOO.OOOO.OOO..',
      ],
      alt: [
        '.....OOOOO.......',
        '...OOBBBBBOO.....',
        '.OOBHHFFFFBOOO...',
        'OBOFFFFFFFFOBBO..',
        'OBOFFFFFFFFOBBO..',
        '.OOFFFFFFFFOSSBOO',
        '.OOFFFFFFFFOBSBBO',
        '.OOBBBBBBBBSOOBO.',
        '..OFBBOBFBBOFBO..',
        '..OOOO.OOOO.OOO..',
      ],
      eyes: [[4, 3], [8, 3]],
      mouth: [6, 5],
    },
    child: {
      body: [
        '.....OOOOO.........',
        '...OOBBBBBOO.......',
        '..OBHHFFFFBOO......',
        '.OOFFFFFFFFOBO.....',
        'OBOFFFFFFFFOBBO....',
        'OBOFFFFFFFFOBBBO...',
        'OBOFFFFFFFFOSSBO.O.',
        'OBOBGGBGGBBOSSBBOBO',
        '.OOBBFGFBBBBOOBBBO.',
        '..OFBBOBFBBOOBFBO..',
        '..OOOO.OOOO..OOOO..',
      ],
      alt: [
        '.....OOOOO.........',
        '...OOBBBBBOO.......',
        '..OBHHFFFFBOO......',
        '.OOFFFFFFFFOBO.....',
        'OBOFFFFFFFFOBBO....',
        'OBOFFFFFFFFOBBBO...',
        '.OOFFFFFFFFOSSBO.O.',
        '.OOBGGBGGBBOBSBBOBO',
        '.OOBBFGFBBBBOOBBBO.',
        '..OFBBOBFBBOOBFBO..',
        '..OOOO.OOOO..OOOO..',
      ],
      eyes: [[4, 3], [8, 3]],
      mouth: [6, 5],
    },
    teen: {
      body: [
        '.....OOOOO...........',
        '...OOBBBBBOO.........',
        '..OBBBBBBBBBO........',
        '.OOBHHFFFFBOBO.......',
        'OBOFFFFFFFFOBBO......',
        'OBOFFFFFFFFOBBBO.....',
        'OBOFFFFFFFFOBBBBOOOO.',
        'OBOFFFFFFFFOSSBBOBOBO',
        'OBOBGGBGGBBOSSBBOO.OO',
        '.OOBBFGFBBBBOOBBOBOBO',
        '..OBBBFBBBBBBBBBBOOO.',
        '..OFBBOBFBBOOOBBFBO..',
        '..OOOO.OOOO...OOOO...',
      ],
      alt: [
        '.....OOOOO...........',
        '...OOBBBBBOO.........',
        '..OBBBBBBBBBO........',
        '.OOBHHFFFFBOBO.......',
        'OBOFFFFFFFFOBBO......',
        'OBOFFFFFFFFOBBBO.....',
        'OBOFFFFFFFFOBBBBOOOO.',
        '.OOFFFFFFFFOSSBBOBOBO',
        '.OOBGGBGGBBOBSBBOO.OO',
        '.OOBBFGFBBBBOOBBOBOBO',
        '..OBBBFBBBBBBBBBBOOO.',
        '..OFBBOBFBBOOOBBFBO..',
        '..OOOO.OOOO...OOOO...',
      ],
      eyes: [[4, 4], [8, 4]],
      mouth: [6, 6],
    },
    adult: {
      body: [
        '......OOOOO...........',
        '....OOBBBBBOO.........',
        '...OBBBBBBBBBO........',
        '..OOBHHFFFFBOBO.......',
        '.OBOFFFFFFFFOBBO......',
        'OBBOFFFFFFFFOBBBO.OO..',
        'OBBOFFFFFFFFOBBBOOOOO.',
        'OBBOFFFFFFFFOSSBOO..OO',
        'OBBOBGGBGGBBOSSBOO..OO',
        'OBOOBBFGFBBBBOOBOBOOBO',
        '.OOBBBBFBBBBBBBBBOOOOO',
        '...OBBBBBBBBBBBBBBBOO.',
        '...OBBBOFBBBOOOBBFO...',
        '...OOOO.OOOO...OOOO...',
      ],
      alt: [
        '......OOOOO...........',
        '....OOBBBBBOO.........',
        '...OBBBBBBBBBO........',
        '..OOBHHFFFFBOBO.......',
        '.OBOFFFFFFFFOBBO......',
        'OBBOFFFFFFFFOBBBO.OO..',
        'OBBOFFFFFFFFOBBBOOOOO.',
        '.OBOFFFFFFFFOSSBOO..OO',
        '.OBOBGGBGGBBOBSBOO..OO',
        'OBOOBBFGFBBBBOOBOBOOBO',
        '.OOBBBBFBBBBBBBBBOOOOO',
        '...OBBBBBBBBBBBBBBBOO.',
        '...OBBBOFBBBOOOBBFO...',
        '...OOOO.OOOO...OOOO...',
      ],
      eyes: [[5, 4], [9, 4]],
      mouth: [7, 6],
    },
  },
}
