import type { Species } from './types'

// Concept: docs/concepts/luma.png. The face is deliberately blank;
// the engine supplies all eyes, blush and mouths in both animation frames.
export const luma: Species = {
  id: 'luma',
  name: '月绒蛾',
  description: '银蓝小绒虫慢慢展开月牙纹圆翅，像一只会扑扇的睡前蝴蝶结。',
  nameEn: 'Luma',
  descriptionEn: 'A silver-blue fluff grows rounded, moon-marked wings and flutters like a tiny bedtime bow.',
  colors: {
    O: 0x3f334e,
    W: 0x7583c9,
    S: 0x535d91,
    B: 0xb4bbde,
    F: 0xcbd7f0,
    H: 0xf4f4ff,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '...OO.....OO...',
        '....OO...OO....',
        '....OBOOOBO....',
        '..OOFFFFFFBOO..',
        '.OHFFFFFFFFBHO.',
        'OWSFFFFFFFFBSWO',
        'OWSFFFFFFFFBSWO',
        '.OSFFFFFFFFBSO.',
        '..OBBBOOBBBBO..',
        '...OOO..OOOO...',
      ],
      alt: [
        '...OO.....OO...',
        '....OO...OO....',
        '....OBOOOBO....',
        '..OOFFFFFFBOO..',
        '.OHFFFFFFFFBHO.',
        '.OSFFFFFFFFBSO.',
        '.OSFFFFFFFFBSO.',
        '.OSFFFFFFFFBSO.',
        '..OBBBOOBBBBO..',
        '...OOO..OOOO...',
      ],
      eyes: [[4, 4], [8, 4]],
      mouth: [6, 6],
    },
    child: {
      body: [
        '....OO.....OO....',
        '.....OO...OO.....',
        '.OOO.OBOOOBO.OOO.',
        'OWHHOFFFFFFBOHHWO',
        'OWHWFFFFFFFFBWHWO',
        'OWSWFFFFFFFFBWSWO',
        'OWSWFFFFFFFFBWSWO',
        '.OSWFFFFFFFFBWSO.',
        '..OWBBBBBBBBBWO..',
        '...OOBBBOBBBOO...',
        '.....OOO.OOO.....',
      ],
      alt: [
        '....OO.....OO....',
        '.....OO...OO.....',
        '.OOO.OBOOOBO.OOO.',
        '.OHHOFFFFFFBOHHO.',
        '.OHWFFFFFFFFBWHO.',
        '.OSWFFFFFFFFBWSO.',
        '.OSWFFFFFFFFBWSO.',
        '.OSWFFFFFFFFBWSO.',
        '..OWBBBBBBBBBWO..',
        '...OOBBBOBBBOO...',
        '.....OOO.OOO.....',
      ],
      eyes: [[5, 4], [9, 4]],
      mouth: [7, 6],
    },
    teen: {
      body: [
        '.....OO.....OO.....',
        '.OOO..OO...OO..OOO.',
        'OWWWO.OBOOOBO.OWWWO',
        'OWHHWOBBBBBBBOWHHWO',
        'OWHWSBFFFFFFBBSWHWO',
        'OWSWSFFFFFFFFBSWSWO',
        '.OSWSFFFFFFFFBSWSO.',
        '.OSWSFFFFFFFFBSWSO.',
        '..OWSFFFFFFFFBSWO..',
        '.OWWWWSBFFFBSWWWWO.',
        '.OWWWWSBBFBBSWWWWO.',
        '..OOOOSBBOBBSOOOO..',
        '......OOO.OOO......',
      ],
      alt: [
        '.....OO.....OO.....',
        '.OOO..OO...OO..OOO.',
        'OWWWO.OBOOOBO.OWWWO',
        '.OHHWOBBBBBBBOWHHO.',
        '.OHWSBFFFFFFBBSWHO.',
        '.OSWSFFFFFFFFBSWSO.',
        '.OSWSFFFFFFFFBSWSO.',
        '.OSWSFFFFFFFFBSWSO.',
        '..OWSFFFFFFFFBSWO..',
        '.OWWWWSBFFFBSWWWWO.',
        '.OWWWWSBBFBBSWWWWO.',
        '..OOOOSBBOBBSOOOO..',
        '......OOO.OOO......',
      ],
      eyes: [[6, 5], [10, 5]],
      mouth: [8, 7],
    },
    adult: {
      body: [
        '.OOO..OO.....OO..OOO.',
        'OWWWO..OO...OO..OWWWO',
        'OWWWWO.OBOOOBO.OWWWWO',
        'OWHHWWOBBBBBBBOWWHHWO',
        'OWHWWSBFFFFFFBBSWWHWO',
        'OWSWWSFFFFFFFFBSWWSWO',
        'OWSWWSFFFFFFFFBSWWSWO',
        '.OSWWSFFFFFFFFBSWWSO.',
        '..OWWSFFFFFFFFBSWWO..',
        '...OWWWSBFFFBSWWWO...',
        '.OOWWWWSBBFBBSWWWWOO.',
        '.OWWWWWSBBBBBSWWWWWO.',
        '..OWWWWSBBBBBSWWWWO..',
        '...OOOOSBBOBBSOOOO...',
        '.......OOO.OOO.......',
      ],
      alt: [
        '.OOO..OO.....OO..OOO.',
        'OWWWO..OO...OO..OWWWO',
        'OWWWWO.OBOOOBO.OWWWWO',
        '.OHHWWOBBBBBBBOWWHHO.',
        '.OHWWSBFFFFFFBBSWWHO.',
        '.OSWWSFFFFFFFFBSWWSO.',
        '.OSWWSFFFFFFFFBSWWSO.',
        '.OSWWSFFFFFFFFBSWWSO.',
        '..OWWSFFFFFFFFBSWWO..',
        '...OWWWSBFFFBSWWWO...',
        '.OOWWWWSBBFBBSWWWWOO.',
        '.OWWWWWSBBBBBSWWWWWO.',
        '..OWWWWSBBBBBSWWWWO..',
        '...OOOOSBBOBBSOOOO...',
        '.......OOO.OOO.......',
      ],
      eyes: [[7, 5], [11, 5]],
      mouth: [9, 7],
    },
  },
}
