import type { Species } from './types'

// Concept: docs/concepts/mallow.png. H is the upper-left highlight;
// O is the warm outline. Facial features are supplied entirely by the engine.
export const mallow: Species = {
  id: 'mallow',
  name: '桃绒狐',
  description: '花瓣耳的小绒团，越长大，奶油尾尖的蓬松卷尾越爱轻轻摇。',
  nameEn: 'Mallow',
  descriptionEn: 'A fluffy kit with petal ears; the older it gets, the more its cream-tipped curly tail wags.',
  colors: {
    O: 0x49303e,
    H: 0xffefdb,
    B: 0xf6b5a4,
    S: 0xb97886,
    T: 0x87566e,
  },
  face: 'H',
  stages: {
    baby: {
      body: [
        '..OO.....OO.....',
        '.OBBO...OBBO....',
        '.OBTBOOOBTBO....',
        '.OBHHHHHHHBO....',
        'OBHHHHHHHHHBO...',
        'OBHHHHHHHHHBOOO.',
        '.OHHHHHHHHHOHHO.',
        '..OHHHHHHHOOBTO.',
        '..OBBHHBBBOBTO..',
        '...OOOOOOOOOO...',
      ],
      alt: [
        '..OO.....OO.....',
        '.OBBO...OBBO....',
        '.OBTBOOOBTBO....',
        '.OBHHHHHHHBO....',
        'OBHHHHHHHHHBO...',
        'OBHHHHHHHHHBO...',
        '.OHHHHHHHHHOOOO.',
        '..OHHHHHHHOHHHO.',
        '..OBBHHBBBOBTO..',
        '...OOOOOOOOOO...',
      ],
      eyes: [[3,4],[7,4]],
      mouth: [5,6],
    },
    child: {
      body: [
        '..OO......OO......',
        '.OBBO....OBBO.....',
        '.OBTBO..OBTBO.....',
        '.OBTBBOOBBTBO.....',
        '..OBHHHHHHBO......',
        '.OBHHHHHHHHBO.OO..',
        'OBHHHHHHHHHHOOHHO.',
        '.OBHHHHHHHHBOHBTO.',
        '..OHHHHHHHHOBTTO..',
        '..OBBHHHBBBOBTOO..',
        '...OOOOOOOOOOO....',
      ],
      alt: [
        '..OO......OO......',
        '.OBBO....OBBO.....',
        '.OBTBO..OBTBO.....',
        '.OBTBBOOBBTBO.....',
        '..OBHHHHHHBO......',
        '.OBHHHHHHHHBO.....',
        'OBHHHHHHHHHHOOOO..',
        '.OBHHHHHHHHBOHHHO.',
        '..OHHHHHHHHOHBTTO.',
        '..OBBHHHBBBOBTOO..',
        '...OOOOOOOOOOO....',
      ],
      eyes: [[4,5],[8,5]],
      mouth: [6,7],
    },
    teen: {
      body: [
        '..OO.......OO.......',
        '.OBBO.....OBBO......',
        '.OBTBO...OBTBO......',
        '.OBTTBO.OBTTBO......',
        '..OBBBOOOBBBO.......',
        '..OBHHHHHHHBO.......',
        '.OBHHHHHHHHHBO..OO..',
        'OBBHHHHHHHHHBBOOHHO.',
        '.OBHHHHHHHHHBOHHBTO.',
        '..OHHHHHHHHHOBBTTTO.',
        '...OBBHHHBBBOBTTOO..',
        '...OBBHHHBBBOTTO....',
        '....OOOOOOOOOOO.....',
      ],
      alt: [
        '..OO.......OO.......',
        '.OBBO.....OBBO......',
        '.OBTBO...OBTBO......',
        '.OBTTBO.OBTTBO......',
        '..OBBBOOOBBBO.......',
        '..OBHHHHHHHBO.......',
        '.OBHHHHHHHHHBO......',
        'OBBHHHHHHHHHBBOOOO..',
        '.OBHHHHHHHHHBOHHHHO.',
        '..OHHHHHHHHHOBBTTTO.',
        '...OBBHHHBBBOBTTOO..',
        '...OBBHHHBBBOTTO....',
        '....OOOOOOOOOOO.....',
      ],
      eyes: [[4,6],[8,6]],
      mouth: [6,8],
    },
    adult: {
      body: [
        '..OO........OO.......',
        '.OBBO......OBBO......',
        '.OBHBO....OBHBO......',
        '.OBTTBO..OBTTBO......',
        '..OBTBBOOBBTBO.......',
        '..OBBBHHBBBBO........',
        '..OBHHHHHHHHBO..OO...',
        '.OBHHHHHHHHHHBOOHHO..',
        'OBBHHHHHHHHHHBBOHHHO.',
        '.OBHHHHHHHHHHBOHBTTO.',
        '..OHHHHHHHHHHOBTTTTO.',
        '...OBBHHHHBBBOBTTTO..',
        '...OBSHHHHBSBOBTTO...',
        '...OBBSHHSBBBOOOO....',
        '....OOOOOOOOOO.......',
      ],
      alt: [
        '..OO........OO.......',
        '.OBBO......OBBO......',
        '.OBHBO....OBHBO......',
        '.OBTTBO..OBTTBO......',
        '..OBTBBOOBBTBO.......',
        '..OBBBHHBBBBO........',
        '..OBHHHHHHHHBO.......',
        '.OBHHHHHHHHHHBO.OOO..',
        'OBBHHHHHHHHHHBBOHHHO.',
        '.OBHHHHHHHHHHBOHHBTO.',
        '..OHHHHHHHHHHOBTTTTO.',
        '...OBBHHHHBBBOBTTTO..',
        '...OBSHHHHBSBOBTTO...',
        '...OBBSHHSBBBOOOO....',
        '....OOOOOOOOOO.......',
      ],
      eyes: [[5,7],[9,7]],
      mouth: [7,9],
    },
  },
}
