import type { Species } from './types'

// Concept: docs/concepts/mossroll.png. The face is deliberately blank;
// the engine supplies all eyes, blush and mouths in both animation frames.
export const mossroll: Species = {
  id: 'mossroll',
  name: '苔卷蜗',
  description: '背着橄榄绿小屋的慢吞吞蜗牛，壳上的卷纹随着长大一圈圈展开。',
  nameEn: 'Mossroll',
  descriptionEn: 'A gentle snail carrying an olive-green home, its shell spiral unfurling as it grows.',
  colors: {
    O: 0x473c32,
    B: 0xb9b09a,
    F: 0xf0e8cf,
    G: 0x99ab66,
    S: 0x60613f,
    H: 0xd9dfa2,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '..OO...OO........',
        '..OO...OO........',
        '..OBOOOBBO..OOO..',
        '.OBFFFFFFBOOHHGO.',
        'OBFFFFFFFFOHHGGGO',
        'OBFFFFFFFFOHHGGGO',
        'OBFFFFFFFFBOGSSGO',
        '.OFFFFFFFFBBOOOOO',
        '.OBBBBBBBBBBBBBO.',
        '..OOOOOOOOOOOOO..',
      ],
      alt: [
        '..O.O..OO........',
        '..O.O..OO........',
        '..OOOOOBBO..OOO..',
        '.OBFFFFFFBOOHHGO.',
        'OBFFFFFFFFOHHGGGO',
        'OBFFFFFFFFOHHGGGO',
        'OBFFFFFFFFBOGSSGO',
        '.OFFFFFFFFBBOOOOO',
        '.OBBBBBBBBBBBBO..',
        '..OOOOOOOOOOOOO..',
      ],
      eyes: [[3, 4], [7, 4]],
      mouth: [5, 6],
    },
    child: {
      body: [
        '.............OOO...',
        '...........OOHGGOO.',
        '..OO...OO.OHHGGGGGO',
        '..OO...OBOOHHGSSSGO',
        '.OBFOOOFFBOGGGGGGSO',
        'OBFFFFFFFFOGGGSSGSO',
        'OBFFFFFFFFBOGGSGGSO',
        'OBFFFFFFFFBOGGGSSOO',
        '.OFFFFFFFFBBOOOOOBO',
        '.OBBBBBBBBBBBBBBBO.',
        '..OOOOOOOOOOOOOOO..',
      ],
      alt: [
        '.............OOO...',
        '...........OOHGGOO.',
        '..O.O..OO.OHHGGGGGO',
        '..OO...OBOOHHGSSSGO',
        '.OBFOOOFFBOGGGGGGSO',
        'OBFFFFFFFFOGGGSSGSO',
        'OBFFFFFFFFBOGGSGGSO',
        'OBFFFFFFFFBOGGGSSOO',
        '.OFFFFFFFFBBOOOOOOO',
        '.OBBBBBBBBBBBBBBO..',
        '..OOOOOOOOOOOOOOO..',
      ],
      eyes: [[3, 5], [7, 5]],
      mouth: [5, 7],
    },
    teen: {
      body: [
        '.............OOOO....',
        '...........OOHGGGOO..',
        '..........OHHGGGGGGO.',
        '..OO...OO.OHHGGGGGGO.',
        '..OO...OBOOGGGGSSSGO.',
        '.OBFOOOFFBOGGGGGGGSO.',
        'OBFFFFFFFFOGGGGSSGSO.',
        'OBFFFFFFFFOGGGGSGGSO.',
        'OBFFFFFFFFBOGGGGSSGO.',
        '.OFFFFFFFFBBOGGGGGOO.',
        '.OBBBBBBBBBBBOOOOOBBO',
        '.OBBBBBBBBBBBBBBBBBO.',
        '..OOOOOOOOOOOOOOOOO..',
      ],
      alt: [
        '.............OOOO....',
        '...........OOHGGGOO..',
        '..........OHHGGGGGGO.',
        '..O.O..OO.OHHGGGGGGO.',
        '..OO...OBOOGGGGSSSGO.',
        '.OBFOOOFFBOGGGGGGGSO.',
        'OBFFFFFFFFOGGGGSSGSO.',
        'OBFFFFFFFFOGGGGSGGSO.',
        'OBFFFFFFFFBOGGGGSSGO.',
        '.OFFFFFFFFBBOGGGGGOO.',
        '.OBBBBBBBBBBBOOOOOBOO',
        '.OBBBBBBBBBBBBBBBBO..',
        '..OOOOOOOOOOOOOOOOO..',
      ],
      eyes: [[3, 6], [7, 6]],
      mouth: [5, 8],
    },
    adult: {
      body: [
        '..............OOO.....',
        '............OOHGGOO...',
        '...........OHHGGGGGO..',
        '..........OHHGGGGGGGO.',
        '..OO...OO.OHHGSSSSGGO.',
        '..OO...OO.OGGGGSSGSGO.',
        '..OBOOOBBOOGGGSGSGSGO.',
        '.OBFFFFFFBOGGGSGGGSGO.',
        'OBFFFFFFFFOOGGGSSSGO..',
        'OBFFFFFFFFOOGGGGGGGO..',
        'OBFFFFFFFFBOOGGGGGO...',
        '.OFFFFFFFFOOBOOOOOBO..',
        '.OBBBBBBBBBBBBBBBBBO..',
        '.OBBBBBBBBBBBBBBBBBBO.',
        '..OOOOOOOOOOOOOOOOOO..',
      ],
      alt: [
        '..............OOO.....',
        '............OOHGGOO...',
        '...........OHHGGGGGO..',
        '..........OHHGGGGGGGO.',
        '..O.O..OO.OHHGSSSSGGO.',
        '..OOO..OO.OGGGGSSGSGO.',
        '..OBOOOBBOOGGGSGSGSGO.',
        '.OBFFFFFFBOGGGSGGGSGO.',
        'OBFFFFFFFFOOGGGSSSGO..',
        'OBFFFFFFFFOOGGGGGGGO..',
        'OBFFFFFFFFBOOGGGGGO...',
        '.OFFFFFFFFOOBOOOOOBO..',
        '.OBBBBBBBBBBBBBBBBBOO.',
        '.OBBBBBBBBBBBBBBBBBBO.',
        '..OOOOOOOOOOOOOOOOOO..',
      ],
      eyes: [[3, 8], [7, 8]],
      mouth: [5, 10],
    },
  },
}
