import type { Species } from './types'

// Concept: docs/concepts/plumcap.png. The face is deliberately blank;
// the engine supplies all eyes, blush and mouths in both animation frames.
export const plumcap: Species = {
  id: 'plumcap',
  name: '绒伞菇',
  description: '顶着紫莓绒伞的小蘑菇，长大后伞沿舒展成软软的波浪。',
  nameEn: 'Plumcap',
  descriptionEn: 'A little mushroom under a plush plum cap that grows into a softly scalloped umbrella.',
  colors: {
    O: 0x48273f,
    B: 0xc779ae,
    S: 0x874969,
    F: 0xeacbf1,
    H: 0xffe8f9,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '.....OOOOO.....',
        '...OOBBBBBOO...',
        '.OOBHHBBBBBBOO.',
        'OBBHBBBBBBBBBBO',
        'OOSSSSSSSSSSSOO',
        '..OFFFFFFFFFO..',
        '..OFFFFFFFFFO..',
        '..OFFFFFFFFFO..',
        '..OFFFFFFFFFO..',
        '...OOOOOOOOO...',
      ],
      alt: [
        '......OOOOO....',
        '....OOBBBBBOO..',
        '..OOBHHBBBBBBOO',
        'OOBHBBBBBBBBBBO',
        'OOSSSSSSSSSSSOO',
        '..OFFFFFFFFFO..',
        '..OFFFFFFFFFO..',
        '..OFFFFFFFFFO..',
        '..OFFFFFFFFFO..',
        '...OOOOOOOOO...',
      ],
      eyes: [[4, 5], [8, 5]],
      mouth: [6, 7],
    },
    child: {
      body: [
        '......OOOOO......',
        '....OOBBBBBOO....',
        '..OOBHHBBBBBBOO..',
        '.OBBHBBBBBBBHBBO.',
        'OBBBBBBBBBBBBBBBO',
        'OOOSSSSSSSSSSSOOO',
        '...OFFFFFFFFFO...',
        '...OFFFFFFFFFO...',
        '...OFFFFFFFFFO...',
        '...OFFFFFFFFFO...',
        '....OOOOOOOOO....',
      ],
      alt: [
        '.......OOOOO.....',
        '.....OOBBBBBOO...',
        '...OOBHHBBBBBBOO.',
        '..OBBHBBBBBBBHBBO',
        'OOBBBBBBBBBBBBBBO',
        'OOOSSSSSSSSSSSOOO',
        '...OFFFFFFFFFO...',
        '...OFFFFFFFFFO...',
        '...OFFFFFFFFFO...',
        '...OFFFFFFFFFO...',
        '....OOOOOOOOO....',
      ],
      eyes: [[5, 6], [9, 6]],
      mouth: [7, 8],
    },
    teen: {
      body: [
        '.......OOOOO.......',
        '.....OOBBBBBOO.....',
        '...OOBBBBBBBHHOO...',
        '..OBBHHBBBBBBBBBO..',
        '.OBBHBBBBBBBBBBBBO.',
        'OBBBBBBBBBBBBBBBBBO',
        'OSSSSSSSSSSSSSSSSSO',
        '.OOOFFFFFFFFFFFOOO.',
        '....OFFFFFFFFFO....',
        '....OFFFFFFFFFO....',
        '...OFFFFFFFFFFFO...',
        '....OFFFFFFFFFO....',
        '.....OOOOOOOOO.....',
      ],
      alt: [
        '........OOOOO......',
        '......OOBBBBBOO....',
        '....OOBBBBBBBHHOO..',
        '...OBBHHBBBBBBBBBO.',
        '..OBBHBBBBBBBBBBBBO',
        'OOBBBBBBBBBBBBBBBBO',
        'OSSSSSSSSSSSSSSSSSO',
        '.OOOFFFFFFFFFFFOOO.',
        '....OFFFFFFFFFO....',
        '....OFFFFFFFFFO....',
        '...OFFFFFFFFFFFO...',
        '....OFFFFFFFFFO....',
        '.....OOOOOOOOO.....',
      ],
      eyes: [[6, 8], [10, 8]],
      mouth: [8, 10],
    },
    adult: {
      body: [
        '.......OOOOOOO.......',
        '.....OOBBBBBBBOO.....',
        '....OBBBBBBBHHBBO....',
        '...OBBHHBBBBBBBBBO...',
        '..OBBBHBBBBBBBBBBBO..',
        '.OBBHBBBBBBBBBBBBBBO.',
        'OBBBBBBBBBBBBBBBBBBBO',
        'OSSOSSSSSSSSSSSSSOSSO',
        '.OO.OFFFFFFFFFFFO.OO.',
        '.....OFFFFFFFFFO.....',
        '.....OFFFFFFFFFO.....',
        '....OFFFFFFFFFFFO....',
        '....OFFFFFFFFFFFO....',
        '.....OFFFFFFFFFO.....',
        '......OOOOOOOOO......',
      ],
      alt: [
        '........OOOOOOO......',
        '......OOBBBBBBBOO....',
        '.....OBBBBBBBHHBBO...',
        '....OBBHHBBBBBBBBBO..',
        '...OBBBHBBBBBBBBBBBO.',
        '..OBBHBBBBBBBBBBBBBBO',
        'OOBBBBBBBBBBBBBBBBBBO',
        'OSSOSSSSSSSSSSSSSOSSO',
        '.OO.OFFFFFFFFFFFO.OO.',
        '.....OFFFFFFFFFO.....',
        '.....OFFFFFFFFFO.....',
        '....OFFFFFFFFFFFO....',
        '....OFFFFFFFFFFFO....',
        '.....OFFFFFFFFFO.....',
        '......OOOOOOOOO......',
      ],
      eyes: [[7, 9], [11, 9]],
      mouth: [9, 11],
    },
  },
}
