import type { Species } from './types'

// Concept: docs/concepts/sprig.png. H is the upper-left highlight;
// O is the warm outline. Facial features are supplied entirely by the engine.
export const sprig: Species = {
  id: 'sprig',
  name: '芽啾',
  description: '一颗会啾啾的小芽，长成顶着双叶、摇着短尾的奶油小鸟。',
  nameEn: 'Sprig',
  descriptionEn: 'A chirping little sprout that grows into a cream bird with two leaves on top and a stubby tail.',
  colors: {
    O: 0x49362f,
    H: 0xfff2ce,
    B: 0xf2c572,
    S: 0xaa7450,
    L: 0x98c993,
    P: 0xefaa85,
  },
  face: 'H',
  stages: {
    baby: {
      body: [
        '......OO.....',
        '.....OLO.....',
        '...OOOBOOO...',
        '..OHHHHHHHOO.',
        '.OHHHHHHHHHBO',
        '.OHHHHHHHHHBO',
        '.OHHHHHHHHHBO',
        '..OHHHHHHHBOO',
        '...OPSOSPSO..',
        '...OOO.OOO...',
      ],
      alt: [
        '.....OO......',
        '.....OLO.....',
        '...OOOBOOO...',
        '..OHHHHHHHOO.',
        '.OHHHHHHHHHBO',
        '.OHHHHHHHHHBO',
        '.OHHHHHHHHHBO',
        '..OHHHHHHHBOO',
        '...OPSOSPSO..',
        '...OOO.OOO...',
      ],
      eyes: [[3,4],[7,4]],
      mouth: [5,6],
    },
    child: {
      body: [
        '....OO..OO.....',
        '...OLLOOLLO....',
        '....OOLLOO.....',
        '...OOOBBOOO....',
        '..OHHHHHHHBO...',
        '.OHHHHHHHHHBO..',
        '.OHHHHHHHHHBO..',
        'OBHHHHHHHHHBBO.',
        'OBSHHHHHHHHBSO.',
        '.OOBPSOOSPBOO..',
        '...OOO..OOO....',
      ],
      alt: [
        '...OO....OO....',
        '...OLOO.OLLO...',
        '....OOLOOOO....',
        '...OOOBBOOO....',
        '..OHHHHHHHBO...',
        '.OHHHHHHHHHBO..',
        '.OHHHHHHHHHBO..',
        'OBHHHHHHHHHBBO.',
        'OBSHHHHHHHHBSO.',
        '.OOBPSOOSPBOO..',
        '...OOO..OOO....',
      ],
      eyes: [[3,5],[7,5]],
      mouth: [5,7],
    },
    teen: {
      body: [
        '....OO...OO........',
        '...OLLO.OLLO.......',
        '....OLLOLLO........',
        '.....OOLOO.........',
        '....OOBBOOO........',
        '...OHHHHHHHOO......',
        '..OHHHHHHHHHBO.....',
        '..OHHHHHHHHHBO.OO..',
        '.OBHHHHHHHHHBBOBO..',
        '.OBSHHHHHHHHHBSOO..',
        '..OBBHHHHHBBSSO....',
        '...OBPSOOSPBOO.....',
        '....OOO..OOO.......',
      ],
      alt: [
        '....OO...OO........',
        '...OLLO.OLLO.......',
        '....OLLOLLO........',
        '.....OOLOO.........',
        '....OOBBOOO........',
        '...OHHHHHHHOO......',
        '..OHHHHHHHHHBO.....',
        '..OHHHHHHHHHBO.....',
        '.OBHHHHHHHHHBBOOO..',
        '.OBSHHHHHHHHBBSOO..',
        '..OBBHHHHHBBSSO....',
        '...OBPSOOSPBOO.....',
        '....OOO..OOO.......',
      ],
      eyes: [[4,6],[8,6]],
      mouth: [6,8],
    },
    adult: {
      body: [
        '....OOO...OOO.......',
        '...OLLLO.OLLLO......',
        '....OLLLOLLLO.......',
        '.....OOOLOOO........',
        '.....OOOBOOO........',
        '....OHHHHHHHOO......',
        '...OBHHHHHHHHBO.....',
        '..OBHHHHHHHHHBBO.OO.',
        '..OBHHHHHHHHHBBBOHO.',
        '.OBBHHHHHHHHHBBSBO..',
        '.OBSBHHHHHHHHBSSBO..',
        '..OSBBHHHHHHBBSSO...',
        '...OBBBSSSSBBBBO....',
        '....OOPOOOOPOOO.....',
        '.....OOO..OOO.......',
      ],
      alt: [
        '...OOO.....OOO......',
        '...OLLOO..OLLLO.....',
        '....OLLLOOLLOO......',
        '.....OOOLOOO........',
        '.....OOOBOOO........',
        '....OHHHHHHHOO......',
        '...OBHHHHHHHHBO.....',
        '..OBHHHHHHHHHBBO....',
        '..OBHHHHHHHHHBBBOOO.',
        '.OBBHHHHHHHHHBBSBHO.',
        '.OBSBHHHHHHHHBSSBO..',
        '..OSBBHHHHHHBBSSO...',
        '...OBBBSSSSBBBBO....',
        '....OOPOOOOPOOO.....',
        '.....OOO..OOO.......',
      ],
      eyes: [[5,7],[9,7]],
      mouth: [7,9],
    },
  },
}
