import type { Species } from './types'

// Concept: docs/concepts/tuck.png. The face is deliberately blank;
// the engine supplies all eyes, blush and mouths in both animation frames.
export const tuck: Species = {
  id: 'tuck',
  name: '眠毯灵',
  description: '住在旧棉毯里的害羞小幽灵，带着小补丁长大，毯角越飘越轻。',
  nameEn: 'Tuck',
  descriptionEn: 'A shy ghost living in an old cotton blanket, growing a tiny mended patch and a softly fluttering hem.',
  colors: {
    O: 0x49383f,
    F: 0xf4f1e8,
    H: 0xfffef9,
    B: 0xc6bfbb,
    S: 0x8b7d85,
    R: 0xbf8587,
  },
  face: 'F',
  stages: {
    baby: {
      body: [
        '....OOOOO....',
        '..OOFFFFFOO..',
        '.OFHHFFFFFBO.',
        'OFFFFFFFFFBBO',
        'OFFFFFFFFFBBO',
        'OFFFFFFFFFBBO',
        'OSFFFFFFFFBBO',
        '.OSRFOFFFOBO.',
        '..OOO.OOO.O..',
      ],
      alt: [
        '....OOOOO....',
        '..OOFFFFFOO..',
        '.OFHHFFFFFBO.',
        'OFFFFFFFFFBBO',
        'OFFFFFFFFFBBO',
        'OFFFFFFFFFBBO',
        'OSFFFFFFFFBOO',
        'OSRFOFFFOBO..',
        '.OOO.OOO.O...',
      ],
      eyes: [[3, 3], [7, 3]],
      mouth: [5, 5],
    },
    child: {
      body: [
        '....OOOOO......',
        '..OOFFFFFOO....',
        '.OFHHFFFFFBO...',
        '.OHFFFFFFFBO...',
        'OFFFFFFFFFBBO..',
        'OFFFFFFFFFFBBO.',
        'OFFFFFFFFFFFBBO',
        'OSFFFFFFFFSFBBO',
        '.OSRFFFFFSFBBO.',
        '.OFFROFFFFOBO..',
        '..OOO.OOOO.OO..',
      ],
      alt: [
        '....OOOOO......',
        '..OOFFFFFOO....',
        '.OFHHFFFFFBO...',
        '.OHFFFFFFFBO...',
        'OFFFFFFFFFBBO..',
        'OFFFFFFFFFFBBO.',
        'OFFFFFFFFFFFBBO',
        'OSFFFFFFFFSFBOO',
        'OSRFFFFFSFBBO..',
        'OFFROFFFFOBO...',
        '.OOO.OOOO.OO...',
      ],
      eyes: [[3, 4], [7, 4]],
      mouth: [5, 6],
    },
    teen: {
      body: [
        '.....OOOOO........',
        '...OOFFFFFOO......',
        '..OFHHFFFFFBO.....',
        '.OFHFFFFFFFBBO....',
        '.OFFFFFFFFFBBO....',
        'OFFFFFFFFFFFBBO...',
        'OFFFFFFFFFFFBBO...',
        'OSFFFFFFFFFFBBO...',
        '.OSSFFFFFFFFFBBO..',
        '.OFRFFFFFFFFFSBBO.',
        '..OFRFFFFFFFSFFBBO',
        '..OFFFFOFFFOOFBBO.',
        '...OOOO.OOO..OOO..',
      ],
      alt: [
        '.....OOOOO........',
        '...OOFFFFFOO......',
        '..OFHHFFFFFBO.....',
        '.OFHFFFFFFFBBO....',
        '.OFFFFFFFFFBBO....',
        'OFFFFFFFFFFFBBO...',
        'OFFFFFFFFFFFBBO...',
        'OSFFFFFFFFFFBBO...',
        '.OSSFFFFFFFFFBBO..',
        '.OFRFFFFFFFFFSBBO.',
        '.OFRFFFFFFFSFFBBO.',
        '.OFFFFOFFFOOFBBO..',
        '..OOOO.OOO..OOO...',
      ],
      eyes: [[4, 4], [8, 4]],
      mouth: [6, 6],
    },
    adult: {
      body: [
        '.....OOOOO...........',
        '...OOFFFFFOO.........',
        '..OHHFFFFFBBO........',
        '.OHFFFFFFFFBBO.......',
        '.OFFFFFFFFFBBO.......',
        'OFFFFFFFFFFFBBO......',
        'OFFFFFFFFFFFFBBO.....',
        'OSFFFFFFFFFFFBBO.....',
        '.OSSFFFFFFFFBBO......',
        '.OFFFFFFFFFFFBBO.....',
        '..ORFFFFFFFFFFFBOO...',
        '..OFRFFFFFFFFFFFSBOO.',
        '.OFFFFFFFFFFFOOOFFBBO',
        '..OOFFFFOFFFO...OBBO.',
        '....OOOO.OOO.....OO..',
      ],
      alt: [
        '.....OOOOO...........',
        '...OOFFFFFOO.........',
        '..OHHFFFFFBBO........',
        '.OHFFFFFFFFBBO.......',
        '.OFFFFFFFFFBBO.......',
        'OFFFFFFFFFFFBBO......',
        'OFFFFFFFFFFFFBBO.....',
        'OSFFFFFFFFFFFBBO.....',
        '.OSSFFFFFFFFBBO......',
        '.OFFFFFFFFFFFBBO.....',
        '..ORFFFFFFFFFFFBOO...',
        '..OFRFFFFFFFFFFFSBOO.',
        'OOFFFFFFFFFFOOOFFBBO.',
        '.OOFFFFOFFFO...OBBO..',
        '...OOOO.OOO.....OO...',
      ],
      eyes: [[3, 4], [7, 4]],
      mouth: [5, 6],
    },
  },
}
